CREATE TABLE IF NOT EXISTS Card (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	scryfall_id VARCHAR(255) DEFAULT NULL,
	location VARCHAR(255) DEFAULT NULL,
	quantity INT NOT NULL DEFAULT 0,
	created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)